# Generated by Django 4.0.5 on 2022-06-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Gorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bordados', models.CharField(max_length=30, verbose_name='Bordados')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('precio', models.FloatField(verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Remera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('estampado', models.CharField(max_length=30, verbose_name='Estampado')),
                ('talle', models.SmallIntegerField(choices=[(1, 'S'), (2, 'M'), (3, 'XL')], verbose_name='Talle')),
                ('precio', models.FloatField()),
            ],
        ),
    ]
