# Generated by Django 4.0.5 on 2022-06-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suikaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gorra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bordado', models.CharField(max_length=30, verbose_name='bordado')),
                ('color', models.CharField(max_length=20, verbose_name='color')),
                ('precio', models.FloatField(verbose_name='precio')),
            ],
        ),
        migrations.DeleteModel(
            name='Gorro',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=30, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='edad',
            field=models.IntegerField(verbose_name='edad'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='nombre'),
        ),
    ]
