# Generated by Django 4.0.5 on 2022-06-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suikaapp', '0002_gorra_delete_gorro_alter_cliente_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gorra',
            name='precio',
            field=models.FloatField(verbose_name='precio $'),
        ),
        migrations.AlterField(
            model_name='remera',
            name='precio',
            field=models.FloatField(verbose_name='precio $'),
        ),
    ]
